name: 🚀 Build and Release OfficeLog

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:
        inputs:
            version:
                description: "Version tag (e.g., v1.0.1)"
                required: true
                default: "v1.0.1"
            prerelease:
                description: "Mark as pre-release"
                required: false
                default: false
                type: boolean

jobs:
    build-and-release:
        name: 📱 Build APK & Create Release
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: 📥 Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 🏷️ Determine Release Version (pre)
              id: version_info
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    VERSION="${{ github.event.inputs.version }}"
                  else
                    VERSION="${GITHUB_REF#refs/tags/}"
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                  echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT
                  echo "Release version (pre): $VERSION"

            - name: 🧾 Read pubspec version
              id: pubspec_version
              run: |
                  PUBSPEC_VERSION_LINE=$(grep -E '^version:' pubspec.yaml)
                  PUBSPEC_VERSION=$(echo "$PUBSPEC_VERSION_LINE" | awk '{print $2}')
                  PUBSPEC_VERSION_NUMBER="${PUBSPEC_VERSION%%+*}"
                  echo "PUBSPEC_VERSION=$PUBSPEC_VERSION" >> $GITHUB_OUTPUT
                  echo "PUBSPEC_VERSION_NUMBER=$PUBSPEC_VERSION_NUMBER" >> $GITHUB_OUTPUT
                  echo "pubspec.yaml version: $PUBSPEC_VERSION"

            - name: ✅ Validate version bump and match
              run: |
                  set -e
                  EXPECTED="${{ steps.version_info.outputs.VERSION_NUMBER }}"
                  PUBSPEC_VERSION_NUMBER="${{ steps.pubspec_version.outputs.PUBSPEC_VERSION_NUMBER }}"
                  echo "Expected version (from input/tag): $EXPECTED"
                  echo "pubspec.yaml version: $PUBSPEC_VERSION_NUMBER"
                  if [ "$PUBSPEC_VERSION_NUMBER" != "$EXPECTED" ]; then
                    echo "❌ Version mismatch. Bump pubspec.yaml to $EXPECTED before running."
                    exit 1
                  fi
                  git fetch --tags --quiet
                  LAST_TAG=$(git tag --list 'v*.*.*' --sort=-v:refname | head -n1)
                  if [ -n "$LAST_TAG" ]; then
                    LAST="${LAST_TAG#v}"
                    if [ "$LAST" = "$EXPECTED" ]; then
                      echo "❌ Version $EXPECTED already exists. Bump the version.";
                      exit 1
                    fi
                    TOP=$(printf "%s\n%s" "$LAST" "$EXPECTED" | sort -V | tail -n1)
                    if [ "$TOP" != "$EXPECTED" ]; then
                      echo "❌ Version $EXPECTED must be greater than last tag $LAST."
                      exit 1
                    fi
                  fi
                  echo "✅ Version validation passed."

            - name: ☕ Set up Java 17
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: 🐦 Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.3"
                  channel: "stable"
                  cache: true

            - name: 🔧 Configure Flutter
              run: |
                  flutter config --no-analytics
                  flutter config --no-cli-animations

            - name: 📦 Install Dependencies
              run: |
                  flutter pub get
                  flutter pub deps
                  flutter doctor

            - name: 🔧 Verify Firebase Configuration
              run: |
                  echo "Checking for google-services.json..."
                  if [ ! -f "android/app/google-services.json" ]; then
                    echo "⚠️ google-services.json not found - building without Firebase features"
                    echo "This is normal for CI builds. Firebase features will be limited."
                    echo "To enable full Firebase features, add google-services.json to the repository."
                  else
                    echo "✅ Firebase configuration file found"
                  fi

            - name: 🧹 Clean Build
              run: flutter clean

            - name: 🔨 Build Release APK
              run: |
                  echo "Building release APK..."
                  flutter build apk --release --verbose
                  echo "✅ APK build completed"

            - name: 📱 Build App Bundle (AAB)
              run: |
                  echo "Building release App Bundle..."
                  flutter build appbundle --release --verbose
                  echo "✅ App Bundle build completed"

            - name: 📊 Get Build Info
              id: build_info
              run: |
                  APK_SIZE=$(du -h build/app/outputs/flutter-apk/app-release.apk | cut -f1)
                  AAB_SIZE=$(du -h build/app/outputs/bundle/release/app-release.aab | cut -f1)
                  echo "APK_SIZE=$APK_SIZE" >> $GITHUB_OUTPUT
                  echo "AAB_SIZE=$AAB_SIZE" >> $GITHUB_OUTPUT
                  echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

            - name: 🏷️ Get Version Info
              id: get_version
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    VERSION="${{ github.event.inputs.version }}"
                  else
                    VERSION="${GITHUB_REF#refs/tags/}"
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                  echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT
                  echo "🏷️ Release version: $VERSION"

            - name: 📝 Generate Release Notes
              id: release_notes
              run: |
                  cat > release_notes.md << EOF
                  ## 🎉 OfficeLog ${{ steps.get_version.outputs.VERSION }}

                  **Built on:** ${{ steps.build_info.outputs.BUILD_DATE }}

                  ### 📱 Download Options
                  - **APK**: ${{ steps.build_info.outputs.APK_SIZE }} - Direct install on Android devices
                  - **AAB**: ${{ steps.build_info.outputs.AAB_SIZE }} - For Google Play Store publishing

                  ### ✨ Features
                  - 👤 **AppBar Profile Picture**: Tap for profile management, long press for admin access
                  - 📍 **Location-based Attendance**: Automatic check-in/check-out using geofencing
                  - 🔄 **Persistent Auto Check-In**: Background service with WorkManager integration
                  - 🔋 **Battery Optimization**: Android battery optimization bypass system
                  - 📊 **Visual Analytics**: Beautiful charts showing attendance patterns
                  - 📅 **Calendar Integration**: Monthly view with attendance tracking
                  - 🔔 **Smart Notifications**: Reminders for check-in/check-out
                  - 🌙 **Dark Mode**: Modern UI with light/dark theme support
                  - 🔐 **Google Sign-In**: Secure authentication
                  - ☁️ **Cloud Sync**: Data synchronized across devices
                  - 🛡️ **Admin Panel**: Secure admin access with holiday and office management

                  ### 📲 Installation Instructions
                  1. Download the APK file below
                  2. Enable "Install from unknown sources" in Android settings
                  3. Install the APK on your Android device
                  4. Grant location permissions when prompted
                  5. Sign in with your Google account

                  ### 📋 System Requirements
                  - **Android**: 5.0+ (API level 21)
                  - **Permissions**: Location, Internet, Storage
                  - **Account**: Google account for authentication
                  - **Storage**: ~100MB free space

                  ### 🔧 Technical Details
                  - **Package**: com.matrimpathak.attendence_flutter
                  - **Version Code**: Built from commit ${{ github.sha }}
                  - **Target SDK**: Android 14 (API 34)
                  - **Minimum SDK**: Android 5.0 (API 21)
                  EOF

            - name: 🚀 Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  name: 🏢 OfficeLog ${{ steps.get_version.outputs.VERSION }}
                  body_path: release_notes.md
                  draft: false
                  prerelease: ${{ github.event.inputs.prerelease == 'true' }}
                  files: |
                      build/app/outputs/flutter-apk/app-release.apk
                      build/app/outputs/bundle/release/app-release.aab
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: 📋 Upload Build Artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: build-outputs-${{ steps.get_version.outputs.VERSION }}
                  path: |
                      build/app/outputs/flutter-apk/
                      build/app/outputs/bundle/
                  retention-days: 30
